import fs from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");

/** Canonical AI media — Desktop Woosh folder (see AGENTS.md). */
export const GENERATED_ROOT = path.join(
  process.env.USERPROFILE ?? process.env.HOME ?? "",
  "Desktop",
  "Woosh",
  "generated by cursor",
);

export const PUBLIC_ASSETS = path.join(ROOT, "public", "assets");

export const STAGING_DIR = path.join(GENERATED_ROOT, "ai-staging");

const SYNC_DIRS = ["services", "posters", path.join("videos", "hero")];

const SYNC_VIDEO_FILES = [
  "car-wash-and-care.mp4",
  "bike-wash-and-care.mp4",
  "auto-wash-and-care.mp4",
  "monthly-packages.mp4",
  "daily-cleaning-services.mp4",
];

export async function ensureGeneratedDirs() {
  await fs.mkdir(STAGING_DIR, { recursive: true });
  await fs.mkdir(path.join(GENERATED_ROOT, "services"), { recursive: true });
  await fs.mkdir(path.join(GENERATED_ROOT, "posters"), { recursive: true });
  await fs.mkdir(path.join(GENERATED_ROOT, "videos", "hero"), { recursive: true });
  await fs.mkdir(path.join(GENERATED_ROOT, "videos"), { recursive: true });
}

async function copyFile(src, dest) {
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.copyFile(src, dest);
}

/** Copy generated media from Desktop Woosh folder into public/assets for the site. */
export async function syncToPublic() {
  for (const dir of SYNC_DIRS) {
    const srcDir = path.join(GENERATED_ROOT, dir);
    const destDir = path.join(PUBLIC_ASSETS, dir);
    let entries;
    try {
      entries = await fs.readdir(srcDir);
    } catch {
      continue;
    }
    for (const name of entries) {
      const src = path.join(srcDir, name);
      const stat = await fs.stat(src);
      if (!stat.isFile()) continue;
      await copyFile(src, path.join(destDir, name));
    }
  }

  for (const name of SYNC_VIDEO_FILES) {
    const src = path.join(GENERATED_ROOT, "videos", name);
    try {
      await fs.access(src);
      await copyFile(src, path.join(PUBLIC_ASSETS, "videos", name));
    } catch {
      // optional file
    }
  }

  console.log(`Synced media → ${PUBLIC_ASSETS}`);
}
