/**
 * Derive site-ready card images (4:5 tiles + 16:9 posters) from today's AI masters.
 * Masters live in the dated _staging folder; outputs go to dated folders and the flat
 * generated media folders that sync-media-to-public reads.
 * Usage: node scripts/process-cards.mjs
 */
import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const DATE = process.env.WOOSH_MEDIA_DATE ?? new Date().toISOString().slice(0, 10);
const GENERATED_ROOT = path.join(
  process.env.USERPROFILE ?? process.env.HOME ?? "",
  "Desktop",
  "Woosh",
  "generated by cursor",
);
const BASE = path.join(GENERATED_ROOT, DATE);
const STAGING = path.join(BASE, "_staging");

const CHARCOAL = { r: 5, g: 10, b: 24 };
const NAVY = { r: 10, g: 22, b: 40 };

// focalX/focalY are 0..1 center points of the crop window within the master.
const SERVICES = [
  {
    slug: "car-wash",
    tileMaster: "tile-car-4x5.png",
    posterMaster: "svc-car-4x5.png",
    fallbackMaster: "svc-car-4x5.png",
    tileFocalX: 0.56,
    tileFocalY: 0.5,
    posterFocalY: 0.48,
  },
  {
    slug: "bike-wash",
    tileMaster: "tile-bike-4x5.png",
    posterMaster: "svc-bike-4x5.png",
    fallbackMaster: "svc-bike-4x5.png",
    tileFocalX: 0.46,
    tileFocalY: 0.5,
    posterFocalY: 0.5,
  },
  {
    slug: "auto-wash",
    tileMaster: "svc-auto-4x5.png",
    posterMaster: "svc-auto-4x5.png",
    fallbackMaster: "svc-auto-4x5.png",
    tileFocalX: 0.38,
    tileFocalY: 0.5,
    posterFocalY: 0.45,
  },
  {
    slug: "daily-cleaning",
    tileMaster: "svc-daily-4x5.png",
    posterMaster: "svc-daily-4x5.png",
    fallbackMaster: "svc-daily-4x5.png",
    tileFocalX: 0.5,
    tileFocalY: 0.5,
    posterFocalY: 0.45,
  },
  {
    slug: "monthly-packages",
    tileMaster: "tile-monthly-4x5.png",
    posterMaster: "svc-monthly-4x5.png",
    fallbackMaster: "svc-monthly-4x5.png",
    tileFocalX: 0.5,
    tileFocalY: 0.5,
    posterFocalY: 0.5,
  },
];

function cropWindow(srcW, srcH, targetRatio, focalX, focalY) {
  // targetRatio = width/height of desired crop
  let cropW = srcW;
  let cropH = Math.round(cropW / targetRatio);
  if (cropH > srcH) {
    cropH = srcH;
    cropW = Math.round(cropH * targetRatio);
  }
  let left = Math.round((srcW - cropW) * focalX);
  let top = Math.round((srcH - cropH) * focalY);
  left = Math.max(0, Math.min(left, srcW - cropW));
  top = Math.max(0, Math.min(top, srcH - cropH));
  return { left, top, width: cropW, height: cropH };
}

async function resolveMaster(primary, fallback) {
  const primaryPath = path.join(STAGING, primary);
  try {
    await fs.access(primaryPath);
    return { path: primaryPath, name: primary };
  } catch {
    const fallbackPath = path.join(STAGING, fallback);
    await fs.access(fallbackPath);
    return { path: fallbackPath, name: fallback };
  }
}

async function radialVignette(width, height, edgeColor, strength) {
  const cx = width / 2;
  const cy = height / 2;
  const maxR = Math.sqrt(cx * cx + cy * cy);
  const pixels = Buffer.alloc(width * height * 4);

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const dx = x - cx;
      const dy = y - cy;
      const t = Math.min(1, Math.sqrt(dx * dx + dy * dy) / maxR);
      const alpha = Math.round(255 * strength * t * t);
      const i = (y * width + x) * 4;
      pixels[i] = edgeColor.r;
      pixels[i + 1] = edgeColor.g;
      pixels[i + 2] = edgeColor.b;
      pixels[i + 3] = alpha;
    }
  }

  return sharp(pixels, { raw: { width, height, channels: 4 } }).png().toBuffer();
}

async function bottomGradient(width, height, color, ratio) {
  const fadeH = Math.round(height * ratio);
  const pixels = Buffer.alloc(width * fadeH * 4);

  for (let y = 0; y < fadeH; y++) {
    const t = y / Math.max(1, fadeH - 1);
    const alpha = Math.round(255 * 0.88 * t * t);
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 4;
      pixels[i] = color.r;
      pixels[i + 1] = color.g;
      pixels[i + 2] = color.b;
      pixels[i + 3] = alpha;
    }
  }

  return sharp(pixels, { raw: { width, height: fadeH, channels: 4 } }).png().toBuffer();
}

async function writeProcessed({ inputPath, outputs, width, height, crop, edgeColor, vignetteStrength, bottomFade }) {
  const vignette = await radialVignette(width, height, edgeColor, vignetteStrength);
  const gradient = await bottomGradient(width, height, CHARCOAL, bottomFade);
  const buffer = await sharp(inputPath)
    .extract(crop)
    .resize(width, height, { fit: "cover" })
    .composite([
      { input: vignette, left: 0, top: 0, blend: "over" },
      {
        input: gradient,
        left: 0,
        top: height - Math.round(height * bottomFade),
        blend: "over",
      },
    ])
    .jpeg({ quality: 90, mozjpeg: true })
    .toBuffer();

  for (const out of outputs) {
    await fs.mkdir(path.dirname(out), { recursive: true });
    await fs.writeFile(out, buffer);
  }
}

async function makeTile(service) {
  const { path: inputPath, name } = await resolveMaster(service.tileMaster, service.fallbackMaster);
  const img = sharp(inputPath);
  const { width, height } = await img.metadata();
  const win = cropWindow(width, height, 4 / 5, service.tileFocalX, service.tileFocalY);
  await writeProcessed({
    inputPath,
    outputs: [
      path.join(BASE, "services", `${service.slug}.jpg`),
      path.join(GENERATED_ROOT, "services", `${service.slug}.jpg`),
    ],
    width: 1200,
    height: 1500,
    crop: win,
    edgeColor: CHARCOAL,
    vignetteStrength: 0.24,
    bottomFade: 0.38,
  });
  console.log(`tile  ${service.slug}.jpg  <- ${name} crop ${win.width}x${win.height}@${win.left},${win.top}`);
}

async function makePoster(service) {
  const { path: inputPath, name } = await resolveMaster(service.posterMaster, service.fallbackMaster);
  const img = sharp(inputPath);
  const { width, height } = await img.metadata();
  const win = cropWindow(width, height, 16 / 9, 0.5, service.posterFocalY);
  await writeProcessed({
    inputPath,
    outputs: [
      path.join(BASE, "posters", `${service.slug}-16x9.jpg`),
      path.join(GENERATED_ROOT, "posters", `${service.slug}-16x9.jpg`),
    ],
    width: 1920,
    height: 1080,
    crop: win,
    edgeColor: NAVY,
    vignetteStrength: 0.18,
    bottomFade: 0.22,
  });
  console.log(`poster ${service.slug}-16x9.jpg  <- ${name} crop ${win.width}x${win.height}@${win.left},${win.top}`);
}

async function main() {
  await fs.mkdir(path.join(BASE, "services"), { recursive: true });
  await fs.mkdir(path.join(BASE, "posters"), { recursive: true });
  await fs.mkdir(path.join(GENERATED_ROOT, "services"), { recursive: true });
  await fs.mkdir(path.join(GENERATED_ROOT, "posters"), { recursive: true });

  for (const s of SERVICES) {
    await makeTile(s);
    await makePoster(s);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
